/*
 * Copyright 2018 Wooga GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.wooga.gradle.test


import com.wooga.gradle.test.queries.PropertyQuery
import com.wooga.gradle.test.writers.BasePropertyWriter
import com.wooga.gradle.test.writers.CustomTaskWriter
import com.wooga.gradle.test.writers.PropertyGetterTaskWriter
import nebula.test.functional.ExecutionResult
import org.gradle.api.Action
import org.junit.Rule
import org.junit.contrib.java.lang.system.EnvironmentVariables
import org.junit.contrib.java.lang.system.ProvideSystemProperty

import static com.wooga.gradle.PlatformUtils.windows

class IntegrationSpec extends nebula.test.IntegrationSpec implements IntegrationHandler {

    @Rule
    ProvideSystemProperty properties = new ProvideSystemProperty("ignoreDeprecations", "true")

    @Rule
    public final EnvironmentVariables environmentVariables = new EnvironmentVariables()

    def setup() {
        environmentVariables.clear()
    }

    static String osPath(String path) {
        if (isWindows()) {
            path = path.startsWith('/') ? "c:" + path : path
        }
        new File(path).path
    }

    /**
     * @param path The path to be composed
     * @return True if the file exists
     */
    Boolean fileExists(String... path) {
        fileExists(path.join(File.separator))
    }

    /**
     * @return True if the standard output or standard error contains the given text
     */
    Boolean outputContains(ExecutionResult result, String text) {
        result.standardOutput.contains(text) || result.standardError.contains(text)
    }

    String wrapValueBasedOnType(Object rawValue, Class type, Closure<String> fallback = null) {
        wrapValueBasedOnType(rawValue, type.simpleName, fallback)
    }

    String wrapValueBasedOnType(Object rawValue, String type, Closure<String> fallback = null) {
        return PropertyUtils.wrapValueBasedOnType(rawValue, type, fallback)
    }

    static File generateBatchWrapper(String fileName, Boolean printEnvironment = false) {
        BatchmodeWrapper wrapper = new BatchmodeWrapper(fileName)
        wrapper.printEnvironment = printEnvironment
        wrapper.toTempFile()
    }
    /**
     * @return The name of the variable holding a reference to the task that was written
     */
    String addTask(String name, Class type, Boolean force, String... lines) {
        addTask(name, type.name, force, lines)
    }

    /**
     * @return The name of the variable holding a reference to the task that was written
     */
    String addTask(String name, String typeName, Boolean force, String... lines) {
        new CustomTaskWriter(name, typeName)
            .force(force)
            .withLines(lines)
            .write(buildFile)
    }

    /**
     * Set a task dependency where A depends on B
     */
    void setTaskDependency(String a, String b) {
        buildFile << """ ${a} { dependsOn ${b} }""".stripIndent()
    }

    /**
     * Appends the lines to the given task
     */
    void appendToTask(String taskName, String... lines) {
        buildFile << """
        $taskName {
            ${lines.join(System.lineSeparator())}
        }
        """.stripIndent()
    }

    /**
     * @param configure A closure to configure the writer
     * @return The name of the variable holding a reference to the task that was written
     */
    String writeTask(String name, String typeName, Action<CustomTaskWriter> configure = null) {
        def writer = new CustomTaskWriter(name, typeName)
        if (configure != null) {
            configure.execute(writer)
        }
        writer.write(buildFile)
    }

    /**
     * @param configure A closure to configure the writer
     * @return The name of the variable holding a reference to the task that was written
     */
    String writeTask(String name, Class type, Action<CustomTaskWriter> configure = null) {
        writeTask(name, type.name, configure)
    }

    /**
     * @param writers A set of writers
     * @param getterWriter A writer that generates a getter
     * @return The names of the tasks that were written to the build script
     */
    List<String> writeTasks(List<BasePropertyWriter> writers, PropertyGetterTaskWriter getterWriter = null) {

        List<String> taskNames = new ArrayList<String>()

        // Write all the task/arguments generated by the other writers
        for (writer in writers) {
            def write = writer.write(this)
            // Returning a result is optional
            if (write != null) {
                taskNames.addAll(write.arguments)
            }
        }

        // Always add the task from the query last
        if (getterWriter != null) {
            taskNames.addAll(getterWriter.write(this).arguments)
        }

        taskNames
    }

    ExecutionResult runTasksSuccessfully(String taskName, List<BasePropertyWriter> writers) {
        List<String> tasksToRun = new ArrayList<String>()
        tasksToRun.add(taskName)
        tasksToRun.addAll(writeTasks(writers))
        runTasksSuccessfully(*tasksToRun)
    }

    ExecutionResult runTasksSuccessfully(String taskName, BasePropertyWriter writer) {
        runTasksSuccessfully(taskName, [writer])
    }

    PropertyQuery runPropertyQuery(PropertyGetterTaskWriter queryTaskWriter, BasePropertyWriter... additional) {
        runPropertyQuery(queryTaskWriter, additional.toList())
    }

    PropertyQuery runPropertyQuery(PropertyGetterTaskWriter queryTaskWriter, List<BasePropertyWriter> writers) {
        List<String> tasks = writeTasks(writers, queryTaskWriter)
        def exec = runTasksSuccessfully(*tasks)
        queryTaskWriter.generateQuery(this, exec)
    }

    PropertyQuery runPropertyQuery(String taskName, PropertyGetterTaskWriter queryTaskWriter, List<BasePropertyWriter> writers) {
        List<String> tasks = writeTasks(writers, queryTaskWriter)
        tasks.add(0, taskName)
        def exec = runTasksSuccessfully(*tasks)
        queryTaskWriter.generateQuery(this, exec)
    }

    PropertyQuery runPropertyQuery(String taskName, PropertyGetterTaskWriter queryTaskWriter, BasePropertyWriter... additional) {
        runPropertyQuery(taskName, queryTaskWriter, additional.toList())
    }
}




